### ISSUE TITLE
Use Decorators instead of vehicle.on_track_piece_change

### ISSUE THREAD

**Issue by jateute** [HHG-TecLap/py-drivesdk#20]
I had the idea that we could use Decorators instead of assigning a function to `vehicle.on_track_piece_change`, because I think it‘ll be easier for the users.

**Comment by PascalRombach** [comment]
Great idea! Will definitely put that into a new branch.
For ease of use for newer people, I would still allow using `Vehicle.on_track_piece_change`.

**Comment by PascalRombach** [comment]
Also, maybe allow multiple on_track_piece_change events when using decorators

**Comment by PascalRombach** [comment]
Closed with #22
