### ISSUE TITLE
uphill-downhill_count in Trackpiece

### ISSUE THREAD

**Issue by albrechtf0** [HHG-TecLap/py-drivesdk#47]
uphill_count and downhill_count should be added to Trackpiece. These values are received for every physical trackpeice and should also be made available in code

**Comment by PascalRombach** [comment]
Testing reveals uphill/downhill is heavily unreliable. This seems to be a bug in the vehicles (again). Unless some resolution is found, this issue will not be implemented.


Possible investigations: Are uphill/downhill floats? That would explain something
